name: LAPRAS Card
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # ここも修正（**を* * *に）
jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate LAPRAS Card
        uses: TA1851/lapras-card-readme@v1  # @mainではなく@v1を試す
        with:
          SHARE_ID: LAPRAS
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 以下オプション
          # ICON_FIRST: "#030E21"
          # ICON_SECOND: "#1688BF"
          # BACKGROUND_FIRST: "#020E27"
          # BACKGROUND_SECOND: "#0E5593"
          # LANG: "ja"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
